apiVersion: batch/v1
kind: Job
metadata:
  name: cc
spec:
  template:
    spec:
      containers:
        - name: content-creator
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "<html>
              <head>
                <title>LAB 6</title>
                <style>
                  body {
                    font-family: Arial, sans-serif;
                    margin: 40px;
                    line-height: 1.6;
                  }
                  h1 {
                    color: #3498db;
                  }
                </style>
              </head>
              <body>
                <h1>K8s Demo - Pawel Jarosz</h1>
                <p>Created at: $(date)</p>
              </body>
              </html>" > /mnt/data/index.html
          volumeMounts:
            - name: web-content
              mountPath: /mnt/data
      restartPolicy: Never
      volumes:
        - name: web-content
          persistentVolumeClaim:
            claimName: web-content-pvc
  backoffLimit: 4
